name: Codex Auto Fix

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed

permissions:
  contents: write
  pull-requests: write

jobs:
  codex-auto-fix:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out triggering commit
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.workflow_run.head_repository.full_name }}
          ref: ${{ github.event.workflow_run.head_sha }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Codex Auto Fix
        uses: openai/openai-codex-action@v1
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          command: codex --auto-fix
          github_token: ${{ secrets.GITHUB_TOKEN }}
